routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\Web\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::prefix('admins')->group(function(){
    Route::prefix('users')
        ->middleware('auth')
        ->name('users.')
        ->group(function () {
            Route::get('/',
                [\App\Http\Controllers\UserController::class, 'index'])
                ->name('index')
                ->middleware('check.permission:index-user');

            Route::get('/{user}/show',
                [\App\Http\Controllers\UserController::class, 'show'])
                ->name('show')
                ->middleware('check.permission:show-user');

            Route::get('/{user}/edit',
                [\App\Http\Controllers\UserController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:edit-user');
            Route::put('/{user}/update',
                [\App\Http\Controllers\UserController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-user');

            Route::get('/create',
                [\App\Http\Controllers\UserController::class, 'create'])
                ->name('create')
                ->middleware('check.permission:create-user');
            Route::post('/',
                [\App\Http\Controllers\UserController::class, 'store'])
                ->name('store')
                ->middleware('check.permission:store-user');

            Route::delete('/{user}',
                [\App\Http\Controllers\UserController::class, 'destroy'])
                ->name('destroy')
                ->middleware('check.permission:delete-user');
        });
    Route::prefix('roles')
        ->middleware('auth')
        ->name('roles.')
        ->group(function () {
            Route::get('/',
                [\App\Http\Controllers\RoleController::class, 'index'])
                ->name('index')
                ->middleware('check.permission:index-role');
            Route::get('/{role}/show',
                [\App\Http\Controllers\RoleController::class, 'show'])
                ->name('show')
                ->middleware('check.permission:show-role');

            Route::get('/{role}/edit',
                [\App\Http\Controllers\RoleController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:edit-role');
            Route::put('/{role}/update',
                [\App\Http\Controllers\RoleController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-role');

            Route::get('/create',
                [\App\Http\Controllers\RoleController::class, 'create'])
                ->name('create')
                ->middleware('check.permission:create-role');
            Route::post('/',
                [\App\Http\Controllers\RoleController::class, 'store'])
                ->name('store')
                ->middleware('check.permission:store-role');

            Route::delete('/{role}',
                [\App\Http\Controllers\RoleController::class, 'destroy'])
                ->name('destroy')
                ->middleware('check.permission:delete-role');

        });

    Route::prefix('products')
        ->middleware('auth')
        ->name('products.')
        ->group(function () {
            Route::get('/',
                [\App\Http\Controllers\ProductController::class, 'index'])
                ->name('index')
                ->middleware('check.permission:index-product');

            Route::get('/list',
                [\App\Http\Controllers\ProductController::class, 'list'])
                ->name('list')
                ->middleware('check.permission:index-product');

            Route::get('/{role}/show',
                [\App\Http\Controllers\ProductController::class, 'show'])
                ->name('show')
                ->middleware('check.permission:show-product');

            Route::get('/{role}/edit',
                [\App\Http\Controllers\ProductController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:edit-product');

            Route::put('/{role}/update',
                [\App\Http\Controllers\ProductController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-product');

            Route::get('/create',
                [\App\Http\Controllers\ProductController::class, 'create'])
                ->name('create')
                ->middleware('check.permission:create-product');

            Route::post('/',
                [\App\Http\Controllers\ProductController::class, 'store'])
                ->name('store')
                ->middleware('check.permission:store-product');

            Route::delete('/{product}',
                [\App\Http\Controllers\ProductController::class, 'destroy'])
                ->name('destroy')
                ->middleware('check.permission:delete-product');

        });

    Route::prefix('categories')
        ->middleware('auth')
        ->name('categories.')
        ->group(function () {
            Route::get('/',
                [\App\Http\Controllers\CategoryController::class, 'index'])
                ->name('index')
                ->middleware('check.permission:index-category');
            Route::get('/children',
                [\App\Http\Controllers\CategoryController::class, 'children'])
                ->name('children')
                ->middleware('check.permission:index-category');


            Route::get('/{role}/show',
                [\App\Http\Controllers\CategoryController::class, 'show'])
                ->name('show')
                ->middleware('check.permission:show-category');

            Route::get('/{category}/edit',
                [\App\Http\Controllers\CategoryController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:edit-category');

            Route::put('/{category}/update',
                [\App\Http\Controllers\CategoryController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-category');

            Route::get('/create',
                [\App\Http\Controllers\CategoryController::class, 'create'])
                ->name('create')
                ->middleware('check.permission:create-category');

            Route::post('/',
                [\App\Http\Controllers\CategoryController::class, 'store'])
                ->name('store')
                ->middleware('check.permission:store-category');

            Route::delete('/{category}',
                [\App\Http\Controllers\CategoryController::class, 'destroy'])
                ->name('destroy')
                ->middleware('check.permission:delete-category');

        });

    Route::prefix('carts')
        ->middleware('auth')
        ->name('carts.')
        ->group(function () {
            Route::get('{id}',
                [CartController::class, 'show'])
                ->name('show')
                ->middleware('check.permission:show-carts');

            Route::get('/',
                [CartController::class, 'index'])
                ->name('index')
                ->middleware('check.permission:index-carts');

        });

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->middleware(['auth:web'])->name('home');

});

Route::prefix('/')->group(function(){
   Route::get('/',[HomeController::class, 'index'])->name('web.home');
});

resources/views/layouts/partials/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <strong>Dang Huu Van <a href="https://www.facebook.com/dangvan.2000">Facebook</a></strong>
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.2.0
    </div>
</footer>

resources/views/layouts/partials/navbar.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{route('home')}}" class="nav-link">Home</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{{route('home')}}"  data-toggle="dropdown">
                {{ Auth::user()->name }}
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

resources/views/layouts/partials/preloader.blade.php
<!-- Preloader -->
<div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__wobble" src="{{asset("assert/dist/img/AdminLTELogo.png")}}" alt="AdminLTELogo" height="60" width="60">
</div>

resources/views/layouts/partials/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{{route('home')}}" class="brand-link">
        <img src="{{asset('assert/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Laravel</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{asset("assert/dist/img/user2-160x160.jpg")}}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="{{route('home')}}" class="d-block">{{auth()->user()->name}}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item menu-open">
                    <a href="{{route('home')}}" class="nav-link {{Route::is('home') || Route::is('home')  ? 'active' : '' }}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                @hasPermission('index-user')
                <li class="nav-item">
                    <a href="{{route('users.index')}}" class="nav-link {{Route::is('users.*') || Route::is('user.*')  ? 'active' : '' }}">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            User
                        </p>
                    </a>
                </li>
                @endhasPermission
                @hasPermission('index-role')
                <li class="nav-item">
                    <a href="{{route('roles.index')}}" class="nav-link {{Route::is('roles.*') || Route::is('roles.*')  ? 'active' : ''}}">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>
                            Role
                        </p>
                    </a>
                </li>
                @endhasPermission
                @hasPermission('index-product')
                <li class="nav-item">
                    <a href="{{route('products.index')}}" class="nav-link {{Route::is('products.*') || Route::is('products.*')  ? 'active' : '' }}">
                        <i class="nav-icon fas fa-chart-pie"></i>
                        <p>
                            Product
                        </p>
                    </a>
                </li>
                @endhasPermission
                @hasPermission('index-category')
                <li class="nav-item">
                    <a href="{{route('categories.index')}}" class="nav-link {{Route::is('categories.*') || Route::is('categories.*')  ? 'active' : '' }}">
                        <i class="nav-icon fas fa-tree"></i>
                        <p>
                            Categories
                        </p>
                    </a>

                </li>
                @endhasPermission

                @hasPermission('index-carts')
                <li class="nav-item">
                    <a href="{{route('carts.index')}}" class="nav-link {{Route::is('carts.*') || Route::is('carts.*')  ? 'active' : '' }}">
                        <i class="nav-icon fas fa-shopping-cart"></i>
                        <p>
                            Carts
                        </p>
                    </a>

                </li>
                @endhasPermission
            </ul>
        </nav>
    </div>
</aside>