routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\Web\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::prefix('admins')->group(function(){
    Route::prefix('users')
        ->middleware('auth')
        ->name('users.')
        ->group(function () {
            Route::get('/',
                [\App\Http\Controllers\UserController::class, 'index'])
                ->name('index')
                ->middleware('check.permission:index-user');

            Route::get('/{user}/show',
                [\App\Http\Controllers\UserController::class, 'show'])
                ->name('show')
                ->middleware('check.permission:show-user');

            Route::get('/{user}/edit',
                [\App\Http\Controllers\UserController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:edit-user');
            Route::put('/{user}/update',
                [\App\Http\Controllers\UserController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-user');

            Route::get('/create',
                [\App\Http\Controllers\UserController::class, 'create'])
                ->name('create')
                ->middleware('check.permission:create-user');
            Route::post('/',
                [\App\Http\Controllers\UserController::class, 'store'])
                ->name('store')
                ->middleware('check.permission:store-user');

            Route::delete('/{user}',
                [\App\Http\Controllers\UserController::class, 'destroy'])
                ->name('destroy')
                ->middleware('check.permission:delete-user');
        });
    Route::prefix('roles')
        ->middleware('auth')
        ->name('roles.')
        ->group(function () {
            Route::get('/',
                [\App\Http\Controllers\RoleController::class, 'index'])
                ->name('index')
                ->middleware('check.permission:index-role');
            Route::get('/{role}/show',
                [\App\Http\Controllers\RoleController::class, 'show'])
                ->name('show')
                ->middleware('check.permission:show-role');

            Route::get('/{role}/edit',
                [\App\Http\Controllers\RoleController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:edit-role');
            Route::put('/{role}/update',
                [\App\Http\Controllers\RoleController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-role');

            Route::get('/create',
                [\App\Http\Controllers\RoleController::class, 'create'])
                ->name('create')
                ->middleware('check.permission:create-role');
            Route::post('/',
                [\App\Http\Controllers\RoleController::class, 'store'])
                ->name('store')
                ->middleware('check.permission:store-role');

            Route::delete('/{role}',
                [\App\Http\Controllers\RoleController::class, 'destroy'])
                ->name('destroy')
                ->middleware('check.permission:delete-role');

        });

    Route::prefix('products')
        ->middleware('auth')
        ->name('products.')
        ->group(function () {
            Route::get('/',
                [\App\Http\Controllers\ProductController::class, 'index'])
                ->name('index')
                ->middleware('check.permission:index-product');

            Route::get('/list',
                [\App\Http\Controllers\ProductController::class, 'list'])
                ->name('list')
                ->middleware('check.permission:index-product');

            Route::get('/{role}/show',
                [\App\Http\Controllers\ProductController::class, 'show'])
                ->name('show')
                ->middleware('check.permission:show-product');

            Route::get('/{role}/edit',
                [\App\Http\Controllers\ProductController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:edit-product');

            Route::put('/{role}/update',
                [\App\Http\Controllers\ProductController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-product');

            Route::get('/create',
                [\App\Http\Controllers\ProductController::class, 'create'])
                ->name('create')
                ->middleware('check.permission:create-product');

            Route::post('/',
                [\App\Http\Controllers\ProductController::class, 'store'])
                ->name('store')
                ->middleware('check.permission:store-product');

            Route::delete('/{product}',
                [\App\Http\Controllers\ProductController::class, 'destroy'])
                ->name('destroy')
                ->middleware('check.permission:delete-product');

        });

    Route::prefix('categories')
        ->middleware('auth')
        ->name('categories.')
        ->group(function () {
            Route::get('/',
                [\App\Http\Controllers\CategoryController::class, 'index'])
                ->name('index')
                ->middleware('check.permission:index-category');
            Route::get('/children',
                [\App\Http\Controllers\CategoryController::class, 'children'])
                ->name('children')
                ->middleware('check.permission:index-category');


            Route::get('/{role}/show',
                [\App\Http\Controllers\CategoryController::class, 'show'])
                ->name('show')
                ->middleware('check.permission:show-category');

            Route::get('/{category}/edit',
                [\App\Http\Controllers\CategoryController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:edit-category');

            Route::put('/{category}/update',
                [\App\Http\Controllers\CategoryController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-category');

            Route::get('/create',
                [\App\Http\Controllers\CategoryController::class, 'create'])
                ->name('create')
                ->middleware('check.permission:create-category');

            Route::post('/',
                [\App\Http\Controllers\CategoryController::class, 'store'])
                ->name('store')
                ->middleware('check.permission:store-category');

            Route::delete('/{category}',
                [\App\Http\Controllers\CategoryController::class, 'destroy'])
                ->name('destroy')
                ->middleware('check.permission:delete-category');

        });

    Route::prefix('carts')
        ->middleware('auth')
        ->name('carts.')
        ->group(function () {
            Route::get('{id}',
                [CartController::class, 'show'])
                ->name('show')
                ->middleware('check.permission:show-carts');

            Route::get('/',
                [CartController::class, 'index'])
                ->name('index')
                ->middleware('check.permission:index-carts');

        });

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->middleware(['auth:web'])->name('home');

});

Route::prefix('/')->group(function(){
   Route::get('/',[HomeController::class, 'index'])->name('web.home');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'products';

    protected $fillable = [
        'name',
        'description',
        'image',
        'price',
    ];

    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_product', 'product_id', 'category_id')->withTimestamps();
    }

    public function hasCategory($categoryId)
    {
        return $this->categories->contains('id', $categoryId);
    }


    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'LIKE', "%{$name}%") : null;
    }

    public function scopeWithCategoryIds($query, $categoryId)
    {
        return $categoryId ? $query->whereHas('categories', fn($q) => $q->where('category_id', $categoryId)) : null;
    }

    public function scopeWithMinPrice($query, $minPrice)
    {
        return $minPrice ? $query->where('price', '>=', $minPrice) : null;
    }

    public function scopeWithMaxPrice($query, $maxPrice)
    {
        return $maxPrice ? $query->where('price', '<=', $maxPrice) : null;
    }

    public function assignCategories($categoryIds)
    {
        return $this->categories()->attach($categoryIds);
    }

    public function syncCategories($categoryIds)
    {
        return $this->categories()->sync($categoryIds);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductCreateRequest;
use App\Http\Requests\ProductUpdateRequest;
use App\Http\Resources\ProductResource;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProductController extends Controller
{
    protected $productService;

    public function __construct(ProductService $productService)
    {
        $this->productService = $productService;
    }

    public function index()
    {
        return view('admin.products.index');
    }

    public function list(Request $request)
    {
        $products = $this->productService->search($request);
        return view('admin.products.list', compact('products'))->render();
    }

    public function show($id)
    {
        $productResource = $this->getResourceById($id);
        return $this->sendSuccessResponse($productResource, 'Thanh cong', Response::HTTP_OK);
    }

    public function store(ProductCreateRequest $request)
    {
        $product = $this->productService->create($request);
        $productResource = $this->getResource($product);
        return $this->sendSuccessResponse($productResource, 'Create success', Response::HTTP_CREATED);
    }

    public function edit($id)
    {
        $productResource = $this->getResourceById($id);
        return $this->sendSuccessResponse($productResource, 'Success', Response::HTTP_OK);
    }

    public function update(ProductUpdateRequest $request, $id)
    {
        $product = $this->productService->update($request, $id);
        $productResource = $this->getResource($product);
        return $this->sendSuccessResponse($productResource, 'Update success', Response::HTTP_OK);
    }

    public function destroy($id)
    {
        $product = $this->productService->delete($id);
        $productResource = $this->getResource($product);
        return $this->sendSuccessResponse($productResource, 'Delete success!', Response::HTTP_OK);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function getById($id)
    {
        return $this->productService->findById($id);
    }

    /**
     * @param $product
     * @return ProductResource
     */
    public function getResource($product): ProductResource
    {
        return new ProductResource($product);
    }

    /**
     * @param $id
     * @return ProductResource
     */
    public function getResourceById($id): ProductResource
    {
        $product = $this->getById($id);
        return $this->getResource($product);
    }
}

resources/views/admin/products/create.blade.php
<div class="modal bd-example-modal-lg fade" id="createProductModal" tabindex="-1" role="dialog"
     aria-labelledby="createProductModalTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createProductModalTitle">Create</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="formCreateProduct" data-action="{{route('products.store')}}" method="POST"
                  enctype="multipart/form-data">
                <div class="modal-body">
                    <section class="content">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card card-primary">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input name="name" type="text" id="name" class="form-control name">
                                        <span class="text-danger name_error_create"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="category_ids">Categories</label>
                                        <select style="width: 100%;" name="category_ids[]"
                                                data-action="{{route('categories.children')}}"
                                                multiple="multiple"
                                                class="form-control select2 categories category_ids">
                                            @foreach($categoryChildren as $item)
                                                <option value="{{$item->id}}">{{$item->name}}</option>
                                            @endforeach
                                        </select>
                                        <span class="text-danger category_ids_error_create"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="price">Price</label>
                                        <input name="price" type="number" id="price" class="form-control price">
                                        <span class="text-danger price_error_create"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="imageCreate"> Image :</label>
                                        <input type="file" class="form-control image" name="image"
                                               placeholder="image Name"
                                               id="imageCreate">
                                        <span class="text-danger image_error_create"></span>
                                    </div>
                                    <div class="form-group container" id="imageCreateShow">
                                    </div>
                                    <div class="form-group">
                                        <label for="description">Description :</label>
                                        <textarea id="description" type="text" class="form-control description"
                                                  name="description"
                                                  value="{{ old('description ') }}">
                                        </textarea>
                                        <span class="text-danger description_error_create"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button id="btn-create-product" type="button" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/products/edit.blade.php
<div class="modal fade bd-example-modal-lg edit-product-modal" id="editProductModal" tabindex="-1" role="dialog" aria-labelledby="editProductModalTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="btn-edit-product-title">Edit</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="formUpdateProduct" method="POST"
                  enctype="multipart/form-data">
                @csrf
            <div class="modal-body">
                <section class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card card-primary">
                                <input type="hidden" id="url" class="url">
                                <div class="form-group">
                                    <label for="nameUpdate">Name</label>
                                    <input name="name" type="text" id="nameUpdate" class="form-control name">
                                    <span class="text-danger name_error_update"></span>
                                </div>
                                <div class="form-group">
                                    <label for="categoryIdUpdate">Categories</label>
                                    <select style="width: 100%;" name="category_ids[]"
                                            multiple="multiple"
                                            class="form-control select2 categories_edit categories">

                                    </select>
                                    <span class="text-danger category_ids_error_update"></span>
                                    <input type="hidden" class="curren" value="" id="currenChildrentId">
                                </div>
                                <div class="form-group">
                                    <label for="priceUpdate">Price</label>
                                    <input name="price" type="number" id="priceUpdate" class="form-control price" >
                                    <span class="text-danger price_error_update"></span>

                                </div>
                                <div class="form-group">
                                    <label for="imageUpdate"> Image :</label>
                                    <input type="file" class="form-control image" name="image" placeholder="image Name"
                                           id="imageUpdate" value="">
                                    <span class="text-danger image_error_update"></span>
                                </div>
                                <div class="form-group container" id="imageUpdateShow">
                                </div>
                                <div class="form-group">
                                    <label for="descriptionUpdate">Description :</label>
                                    <textarea id="descriptionUpdate" type="text" class="form-control description"
                                              name="description">
                                    </textarea>
                                    <span class="text-danger description_error_update"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="btn-update-product" type="button" class="btn btn-primary btn-update-product">Save changes</button>
            </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/products/index.blade.php
@extends('layouts.teamplate')

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Product</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                        <li class="breadcrumb-item active">Product</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <div class="card products-list">
        <section class="content">
            <div class="container-fluid">
        <div class="card-header border-transparent">
            <form id="searchProduct" data-action="{{route('products.list')}}">
                <div class="form-group search-product">
                    <div class="input-group input-group-sm">
                        <input name="name" type="search" class="form-control form-control-lg name-search"
                               placeholder="Search by name" value="{{request('name')}}">
                        <input name="min_price" type="search" class="form-control form-control-lg min-price-search"
                               placeholder="Search by min price" value="{{request('min_price')}}">
                        <select name="category_id" id="category_id" value="{{request('category_id')}}" class="form-control form-control-lg categories">
                            <option value="0">Select All</option>
                            @foreach($categoryChildren as $item)
                                <option value="{{$item->id}}">{{$item->name}}</option>
                            @endforeach
                        </select>
                        <input name="max_price" type="search" class="form-control form-control-lg max-price-search"
                               placeholder="Search by max price" value="{{request('max_price')}}">

                    </div>
                </div>
            </form>
        </div>
            </div>
        </section>

        <div class="card-footer clearfix">
            <div class="float-lg-left" id="success_message"></div>
            <button id="createProduct" type="button" class="btn btn-primary float-right createProduct" data-toggle="modal"
                    data-target="#createProductModal">
                <i class="fas fa-plus"></i> Create
            </button>
        </div>
        @include('admin.products.show')
        @include('admin.products.create')
        @include('admin.products.edit')
        <div class="card-body p-0 list-product" id="list" data-action="{{route('products.list')}}">
        </div>


    </div>

@endsection
@push('scripts')
    <script src="{{asset('admin/js/pagination.js')}}"></script>
    <script  src="{{asset("admin/js/product.js")}}"></script>
@endpush

resources/views/admin/products/list.blade.php
@php
    $stt = (($_GET['page']?? 1)-1)*5;
@endphp
<div class="card-body p-0 list-product" id="list" data-action="{{route('products.list')}}">
    <div class="table-responsive">
        <table class="table m-0 table table-bordered table-hover">
            <thead>
            <tr class="text-center">
                <th>ID</th>
                <th>image</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Categories</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($products as $product)
                <tr id="id{{$product->id}}">
                    <td class="text-center">{{++$stt}}</td>
                    <td class="text-center"><img height="50px" width="50px"
                             src="{{ $product->image == 'default.jpg' ? url('images/default.jpg') : url('images/'.$product->image)}}">
                    </td>

                    <td class="text-center">{{$product->name}}</td>
                    <td style="overflow: auto">{{\Illuminate\Support\Str::limit($product->description,30)}}</td>
                    <td>{{$product->price}}</td>
                    <td>
                        @foreach($product->categories as $category)
                            <span class="badge badge-success">{{$category->name}}</span>
                        @endforeach
                    </td>
                    <td class="text-center">
                        <button class="btn btn-secondary" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            @hasPermission('show-product')
                            <a type="button" class="dropdown-item show-product" data-toggle="modal"
                               data-target="#showProductModal" id="showProductModal"
                               data-action="{{route('products.show',$product->id)}}"
                               onclick="Product.getShow($(this))"
                            ><i
                                    class="fas fa-folder">
                                </i>
                                View</a>
                            @endhasPermission
                            @hasPermission('edit-product')
                            <a class="dropdown-item edit-product" type="button"
                               data-toggle="modal" data-target="#editProductModal"
                               data-action2="{{route('products.update',$product->id)}}"
                               id="editProduct" data-action="{{route('products.show',$product->id)}}"
                            ><i
                                    class="fas fa-pencil-alt"></i>Edit</a>
                            @endhasPermission
                            @hasPermission('delete-product')
                            <a type="button" class="dropdown-item delete-product"
                               data-action="{{route('products.destroy',$product->id)}}"
                            ><i
                                    class="fas fa-trash">
                                </i>
                                Delete</a>
                            @endhasPermission
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{$products->appends(request()->all())->links()}}
    </div>
</div>

resources/views/admin/products/show.blade.php
<div class="modal fade bd-example-modal-lg show-product-modal" id="showProductModal" tabindex="-1" role="dialog" aria-labelledby="showProductModalTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content ">
            <div class="modal-header">
                <h5 class="modal-title" id="btn-edit-product-title">Show</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
                <div class="modal-body">
                    <section class="content">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card card-primary">
                                    <div class="form-group">
                                        <label for="nameShow">Name :</label>
                                        <p id="nameShow"></p>
                                    </div>
                                    <div class="form-group">
                                        <label for="categoriesShow">Categories :</label>
                                        <div id="categoriesShow">

                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="priceShow">Price :</label>
                                        <p id="priceShow"></p>
                                    </div>
                                    <div class="form-group">
                                        <img id="imageShow" width="100%" height="300px" src="" alt="show img product">
                                    </div>
                                    <div class="form-group">
                                        <label for="descriptionShow">Description :</label>
                                        <textarea id="descriptionShow" disabled type="text" class="form-control">
                                        </textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
        </div>
    </div>
</div>